CREATE TABLE PHONE_MODELS
(
	PHONE_ID INT PRIMARY KEY,
	NAME VARCHAR(100),
	COUNTRY VARCHAR(100)
)

CREATE TABLE PHONE_DET
(
	PHONE_ID INT ,
	DATE_DELIVERY DATE,
	QUANTITY INT,
	PRICE INT ,
	COLOR VARCHAR(100),
	INSTALLMENT VARCHAR(100),
	INITIAL_PAYMENT INT
	FOREIGN KEY (PHONE_ID) REFERENCES PHONE_MODELS(PHONE_ID)
	);

--1 SELECT * FROM PHONE_DET
--2	SELECT PHONE_ID FROM PHONE_DET
--	WHERE DATE_DELIVERY = '2015-03-15';
--3 SELECT PHONE_ID FROM PHONE_MODELS
--  WHERE LEFT(COUNTRY, 1) = 'K';
--4 SELECT PD.PHONE_ID, PM.NAME FROM PHONE_DET PD
-- JOIN PHONE_MODELS PM ON PD.PHONE_ID= PM.PHONE_ID
--  WHERE PRICE > 10000000 AND DATE_DELIVERY = '2015-01-01' AND COLOR = 'BLACK'
--5 SELECT PRICE FROM PHONE_DET
--  WHERE DATE_DELIVERY BETWEEN '2015-09-01' AND '2015-09-15' AND (COLOR = 'RED' OR COLOR='GREEN') AND INSTALLMENT='YES';
--6 SELECT PM.NAME FROM PHONE_MODELS PM
--  INNER JOIN PHONE_DET PD ON PM.PHONE_ID = PD.PHONE_ID
--  WHERE DATE_DELIVERY = '2015-02-01' AND PM.COUNTRY = 'CHINA'
-- ORDER BY PD.PRICE DESC 
--7  SELECT pm.NAME FROM PHONE_MODELS pm
--  JOIN PHONE_DET pd ON pm.PHONE_ID = pd.PHONE_ID
--  WHERE pd.INSTALLMENT = 'YES' AND pd.COLOR IS NOT NULL
--  ORDER BY pd.INITIAL_PAYMENT ASC;
--8 SELECT PHONE_ID 
-- FROM PHONE_MODELS 
-- WHERE PHONE_ID NOT IN (SELECT DISTINCT PHONE_ID FROM PHONE_DET);
--9 INSERT INTO PHONE_MODELS (PHONE_ID, NAME, COUNTRY) 
--  VALUES (5000, 'APPLE_6S', 'CHINA');
--10 UPDATE PHONE_DET 
--   SET PRICE = 20000000, INITIAL_PAYMENT = 2000000
--   WHERE PHONE_ID = 533;